POS/POS.Web/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using POS.Repository;
using POS.Service;
using POS.ViewModel;

namespace POS.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly EmployeeService _service;
        public EmployeeController(ApplicationContext context)
        {
            _service = new EmployeeService(context);
        }

        [HttpGet]
        public IActionResult Index()
        {
            var data = _service.GetAllEmployee();
            return View(data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return PartialView("Add");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind("LastName, FirstName, Title, TitleOfCourtesy, BirthDate, HireDate, Address, City, Region, PostalCode, Country, HomePhone, Notes, ReportTo")]EmployeeModel request)
        {
            if (ModelState.IsValid)
            {
                _service.Add(new EmployeeEntity(request));
                return Redirect("Index");
            }
            return View("Add", request);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            var data = _service.GetEmployee(id);
            return View(data);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var data = _service.Edit(id);
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update([Bind("Id, LastName, FirstName, Title, TitleOfCourtesy, BirthDate, HireDate, Address, City, Region, PostalCode, Country, HomePhone, Notes, ReportTo")]EmployeeModel request)
        {
            if (ModelState.IsValid)
            {
                _service.Update(request);
                return Redirect("Index");
            }
            return View("Edit", request);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            _service.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

POS/POS.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using POS.Repository;
using POS.Service;
using POS.ViewModel;

namespace POS.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly OrderService _orderService;
        private readonly CustomerService _customerService;
        private readonly EmployeeService _employeeService;
        private readonly ShipperService _shipperService;
        private readonly ProductService _productService;

        public OrderController(ApplicationContext context)
        {
            _orderService = new OrderService(context);
            _customerService = new CustomerService(context);
            _employeeService = new EmployeeService(context);
            _shipperService = new ShipperService(context);
            _productService = new ProductService(context);
        }

        [HttpGet]
        public IActionResult Index()
        {
            var orders = _orderService.GetOrders();
            return View(orders);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Customer = new SelectList(_customerService.GetAllCustomer(), "Id", "Name");
            ViewBag.Employee = new SelectList(_employeeService.GetAllEmployee(), "Id", "LastName");
            ViewBag.Shipper = new SelectList(_shipperService.GetAllShipper(), "Id", "CompanyName");
            ViewBag.Product = new SelectList(_productService.GetProducts(), "Id", "ProductName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(
            [Bind("CustomerId, EmployeeId, OrderDate, RequiredDate, ShippedDate, ShipperId, Freight, ShipName, ShipAddress, ShipCity, ShipRegion, ShipPostalCode, ShipCountry, OrderDetails")] OrderModel request)
        {
            if (ModelState.IsValid)
            {
                _orderService.CreateOrder(request);
                return Redirect("Index");
            }
            return View("Add", request);
        }

        /*[HttpGet]
        public IActionResult Details(int? id)
        {
            var order = _orderService.ReadOrder(id);
            return View(order);
        }*/
        [HttpGet]
        public IActionResult Details(int? id)
        {
            var order = _orderService.ReadOrderInvoice(id);
            return View(order);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.Customer = new SelectList(_customerService.GetAllCustomer(), "Id", "Name");
            ViewBag.Employee = new SelectList(_employeeService.GetAllEmployee(), "Id", "LastName");
            ViewBag.Shipper = new SelectList(_shipperService.GetAllShipper(), "Id", "CompanyName");
            ViewBag.Product = new SelectList(_productService.GetProducts(), "Id", "ProductName");
            var order = _orderService.ReadOrder(id);

            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update([Bind("Id, CustomerId, EmployeeId, OrderDate, RequiredDate, ShippedDate, ShipperId, Freight, ShipName, ShipAddress, ShipCity, ShipRegion, ShipPostalCode, ShipCountry, OrderDetails")] OrderModel request)
        {
            if (ModelState.IsValid)
            {
                _orderService.UpdateOrder(request);
                return Redirect("Index");
            }
            return View("Edit", request);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            _orderService.DeleteCategory(id);
            return Redirect("/Order");
        }
    }
}

POS/POS.Web/Views/Order/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model POS.ViewModel.OrderModel

@{
    ViewBag.Title = "Orders";
    Layout = "_Layout";
}

<h2>Form Add Order</h2>

<form asp-controller="Order" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CustomerId">Customer</label>
        <select type="text" asp-for="CustomerId" class="form-control" asp-items="@ViewBag.Customer">
            <option selected>Select Customer</option>
        </select>
        <span asp-validation-for="CustomerId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EmployeeId">Employee</label>
        <select type="text" asp-for="EmployeeId" class="form-control" asp-items="@ViewBag.Employee">
            <option selected>Select Employee</option>
        </select>
        <span asp-validation-for="EmployeeId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="OrderDate">Order Date</label>
        <input asp-for="OrderDate" class="form-control" />
        <span asp-validation-for="OrderDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="RequiredDate">Required Date</label>
        <input asp-for="RequiredDate" class="form-control" />
        <span asp-validation-for="RequiredDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippedDate">Shipped Date</label>
        <input asp-for="ShippedDate" class="form-control" />
        <span asp-validation-for="ShippedDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShipperId">Shipper</label>
        <select type="text" asp-for="ShipperId" class="form-control" asp-items="@ViewBag.Shipper">
            <option selected>Select Shipper</option>
        </select>
        <span asp-validation-for="ShipperId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Freight">Freight</label>
        <input asp-for="Freight" class="form-control" />
        <span asp-validation-for="Freight" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShipName">Ship Name</label>
        <input asp-for="ShipName" class="form-control" />
        <span asp-validation-for="ShipName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShipAddress">Ship Address</label>
        <input asp-for="ShipAddress" class="form-control" />
        <span asp-validation-for="ShipAddress" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShipCity">Ship City</label>
        <input asp-for="ShipCity" class="form-control" />
        <span asp-validation-for="ShipCity" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShipRegion">Ship Region</label>
        <input asp-for="ShipRegion" class="form-control" />
        <span asp-validation-for="ShipRegion" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShipPostalCode">Ship Postal Code</label>
        <input asp-for="ShipPostalCode" class="form-control" />
        <span asp-validation-for="ShipPostalCode" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShipCountry">Ship Country</label>
        <input asp-for="ShipCountry" class="form-control" />
        <span asp-validation-for="ShipCountry" class="text-danger"></span>
    </div>

    <h2 class="content-caption mb-0 d-flex justify-content-between">
        Order Detail
        <a class="btn-add add-detail" data-added="0"><i class="la la-plus la-lg">+</i></a>
    </h2>

    <table class="table table-borderless m-0" id="tbl_posts2">
        <thead>
            <tr>
                <th>Product ID</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Discount</th>
            </tr>
        </thead>
        <tbody id="tbl_posts_body2">
            <tr id="re-0">
                <td>
                    <select type="text" asp-for="OrderDetails[0].ProductId" class="form-control" asp-items="@ViewBag.Product">
                        <option selected>Select the Product</option>
                    </select>
                </td>
                <td><input asp-for="OrderDetails[0].UnitPrice" class="form-control" /></td>
                <td><input asp-for="OrderDetails[0].Quantity" class="form-control" /></td>
                <td><input asp-for="OrderDetails[0].Discount" class="form-control" /></td>
                <td class="text-center"><a class="btn btn-xs delete-detail" edu-data-id="1"><i class="la la-trash la-lg text-danger">-</i></a></td>
            </tr>

        </tbody>
        <tbody id="Detail-2">
        </tbody>

    </table>

    <div class="pt-2 pb-2">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

@section Scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {

            //Education
            var j = 1;
            //added class to inputs
            $('a.add-detail').click(function () {
                $("#Detail-2").append('<tr><td><input id="OrderDetails_' + j + '__ProductId" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].ProductId" value=""/></td><td><input id="OrderDetails_' + j + '__UnitPrice" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].UnitPrice" value=""/></td><td><input id="OrderDetails_' + j + '__Quantity" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Quantity" value=""/></td><td><input id="OrderDetails_' + j + '__Discount" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Discount" value=""/></td><td class="text-center"><a class="btn btn-xs delete-detail" edu-data-id="1"><i class="la la-trash la-lg text-danger">-</i></a></td></tr>');
                j++;
            });
            $('#Detail-2').on('click', '.delete-detail', function () {
                $(this).parent().parent().remove();
                j--; //decremnt count
                resetValues(); //call to reset values
            });

            function resetValues() {
                counter = 1; //initialze to 1
                //looping through tbody
                $("#Detail-2 tr").each(function () {
                    //find .school class replace its name value
                    $(this).find('.ProductId').attr("OrderDetails[" + counter + "].ProductId");
                    $(this).find('.UnitPrice').attr("OrderDetails[" + counter + "].UnitPrice");
                    $(this).find('.Quantity').attr("OrderDetails[" + counter + "].Quantity");
                    $(this).find('.Discount').attr("OrderDetails[" + counter + "].Discount");
                    counter++; //increment count
                })
            }
        });
    </script>
}

POS/POS.Web/Views/Order/Details.cshtml
@model POS.ViewModel.Response.OrderResponse
@{
    ViewBag.Title = "Order Detail";
    Layout = "_Layout";
}

<div class="invoice p-3 mb-3">
    <!-- title row -->
    <div class="row">
        <div class="col-12">
            <h4>
                <i class="fas fa-globe"></i> RapidTech Commerce
                <small class="float-right">Date: @Model.OrderDate</small>
            </h4>
        </div>
        <!-- /.col -->
    </div>
    <!-- info row -->
    <div class="row invoice-info">
        <div class="col-sm-3 invoice-col">
            From
            <address>
                <strong>E-commerce's Warehouse</strong><br>
                Jalan Buntu<br>
                Phone: (021) 717125 <br>
                Email: ecommerce@mail.com
            </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-3 invoice-col">
            To
            <address>
                <strong>@Model.ShipName</strong><br>
                @Model.ShipAddress, @Model.ShipCity<br>
                @Model.ShipRegion, @Model.ShipCountry, @Model.ShipPostalCode<br>
            </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-3 invoice-col">
            Send by
            <address>
                <strong>@Model.ShipperName</strong><br>
                Phone: @Model.ShipperPhone
            </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-3 invoice-col">
            <b>Invoice # @Model.Id</b><br>
            <br>
            <b>Order ID:</b> @Model.Id<br>
            <b>Payment Due:</b> @Model.RequiredDate<br>
            <b>Account:</b> @Model.CustomerId;
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    <!-- Table row -->
    <div class="row">
        <div class="col-12 table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Qty</th>
                        <th>Product</th>
                        <th>Product ID #</th>
                        <th>Discount (%)</th>
                        <th>Price per Item (Rp)</th>
                        <th>Subtotal (Rp)</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Details)
                    {
                        <tr>
                            <td>@item.Quantity</td>
                            <td>@item.ProductName</td>
                            <td>@item.ProductId</td>
                            <td>@item.Discount</td>
                            <td>@item.UnitPrice</td>
                            <td>@item.Subtotal</td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

    <div class="row">
        <!-- accepted payments column -->
        <div class="col-6">
            <p class="lead">Payment Methods:</p>
            <p>Dana</p>
            <p>GoPay</p>
            <p>Ovo</p>
            <p>Transfer Bank</p>

        </div>
        <!-- /.col -->
        <div class="col-6">
            <p class="lead">Amount Due @Model.RequiredDate</p>

            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th style="width:50%">Subtotal:</th>
                        <td>Rp @Model.Subtotal</td>
                    </tr>
                    <tr>
                        <th>Tax (10%)</th>
                        <td>Rp @Model.Tax</td>
                    </tr>
                    <tr>
                        <th>Shipping:</th>
                        <td>Rp @Model.Shipping</td>
                    </tr>
                    <tr>
                        <th>Total:</th>
                        <td>Rp @Model.Total</td>
                    </tr>
                </table>
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    <!-- this row will not appear when printing -->
    <div class="row no-print">
        <div class="col-12">
            @*<a href="invoice-print.html" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>*@
            <button type="button" class="btn btn-success float-right">
                <i class="far fa-credit-card"></i> Submit
                Payment
            </button>
            <button type="button" class="btn btn-primary float-right" style="margin-right: 5px;">
                <i class="fas fa-download"></i> Generate PDF
            </button>
        </div>
    </div>
</div>
<!-- /.invoice -->

POS/POS.Web/Views/Order/Edit.cshtml
@model POS.ViewModel.OrderModel
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<h2>Edit Order</h2>
<form asp-controller="Employee" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="CustomerId">Customer ID</label>
        <input asp-for="CustomerId" class="form-control" />
        <span asp-validation-for="CustomerId" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="EmployeeId">Employee ID</label>
        <input asp-for="EmployeeId" class="form-control" />
        <span asp-validation-for="EmployeeId" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="OrderDate">Order Date</label>
        <input asp-for="OrderDate" class="form-control" />
        <span asp-validation-for="OrderDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="RequiredDate">Required Date</label>
        <input asp-for="RequiredDate" class="form-control" />
        <span asp-validation-for="RequiredDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShippedDate">Shipped Date</label>
        <input asp-for="ShippedDate" class="form-control" />
        <span asp-validation-for="ShippedDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipperId">Shipper ID</label>
        <input asp-for="ShipperId" class="form-control" />
        <span asp-validation-for="ShipperId" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Freight"></label>
        <input asp-for="Freight" class="form-control" />
        <span asp-validation-for="Freight" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipName">Ship Name</label>
        <input asp-for="ShipName" class="form-control" />
        <span asp-validation-for="ShipName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipAddress">Ship Address</label>
        <input asp-for="ShipAddress" class="form-control" />
        <span asp-validation-for="ShipAddress" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipCity">Shio City</label>
        <input asp-for="ShipCity" class="form-control" />
        <span asp-validation-for="ShipCity" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipRegion">Ship Region</label>
        <input asp-for="ShipRegion" class="form-control" />
        <span asp-validation-for="ShipRegion" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipPostalCode">Ship Postal Code</label>
        <input asp-for="ShipPostalCode" class="form-control" />
        <span asp-validation-for="ShipPostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipCountry">Ship Country</label>
        <input asp-for="ShipCountry" class="form-control" />
        <span asp-validation-for="ShipCountry" class="text-danger" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.Web/Views/Order/Index.cshtml
@model IEnumerable<POS.Repository.OrderEntity>
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Order List</h2>
<div class="pt-2 pb-2">
    <a asp-action="Add" class="btn btn-primary" role="button" id="btn-add">Add Order </a>
</div>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>Customer ID</th>
            <th>Employee ID</th>
            <th>Order Date</th>
            <th>Required Date</th>
            <th>Shipped Date</th>
            <th>Shipper ID</th>
            <th>Freigt</th>
            <th>Ship Name</th>
            <th>Ship Address</th>
            <th>Ship City</th>
            <th>Ship Region</th>
            <th>Ship Postal Code</th>
            <th>Ship Country</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.CustomerId</td>
                <td>@item.EmployeeId</td>
                <td>@item.OrderDate</td>
                <td>@item.RequiredDate</td>
                <td>@item.ShippedDate</td>
                <td>@item.ShipperId</td>
                <td>@item.Freight</td>
                <td>@item.ShipName</td>
                <td>@item.ShipAddress</td>
                <td>@item.ShipCity</td>
                <td>@item.ShipRegion</td>
                <td>@item.ShipPostalCode</td>
                <td>@item.ShipCountry</td>
                <td>
                    <div class="d-flex">
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning me-2">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success me-2">View</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger me-2">Delete</a>
                    </div>
                    
                </td>
            </tr>
        }
    </tbody>
</table>

<div id="my-modal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>

        </div>
    </div>
</div>